name: cicd-demo

on:
  push:
    branches:
      - main

env:
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.3.0
        id: get-ocir-repository
        with:
          name: "spring-projects/spring-boot-hello-app"
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      ...

