name: Build and Deploy to OKE using OCI CLI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
        cat > ~/.oci/config <<EOF
[DEFAULT]
user=${{ secrets.OCI_CLI_USER }}
fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
key_file=~/.oci/oci_api_key.pem
tenancy=${{ secrets.OCI_CLI_TENANCY }}
region=${{ secrets.OCI_CLI_REGION }}
EOF

    - name: Generate kubeconfig
      run: |
        oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OKE_CLUSTER_OCID }} --file $HOME/.kube/config --region ${{ secrets.OCI_CLI_REGION }} --token-version 2.0.0 --kube-endpoint PUBLIC_ENDPOINT
        chmod 600 $HOME/.kube/config

    - name: Build Docker image
      run: |
        docker build -t fra.ocir.io/frvwt5kzjktn/spring-projects/spring-boot-hello-app:latest .

    - name: Login and Push to OCIR
      run: |
        echo "${{ secrets.OCI_AUTH_TOKEN }}" | docker login fra.ocir.io -u "${{ secrets.OCI_CLI_USER }}" --password-stdin
        docker push fra.ocir.io/frvwt5kzjktn/spring-projects/spring-boot-hello-app:latest

    - name: Deploy to OKE
      run: |
        kubectl apply -f spring-app.yaml

